name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment on PR targeting the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1



      - name: Install zip (if not already installed)
        run: sudo apt-get install -y zip

      - name: Create deployment package
        run: |
          zip -r function.zip .  # Zip the contents of the repository (adjust if needed)

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name helloworldfunction \
            --zip-file fileb://function.zip \
            --region us-east-1  # Ensure you use the correct region
      - name: Deploy API Gateway
        run: |
         aws apigatewayv2 create-deployment --api-id 4jjrp06d1j --stage-name DEV
